import type { Building } from "./types";

// Colin's own buildings: the ideas that already exist. Lots are assigned in
// this order along the town's spiral, so the first entries sit at the centre.
// Who runs each of Colin's buildings. Used to lay out their insides.
export const SEED_KEEPERS: Record<string, { name: string; greeting: string }> = {
  "the-loop": { name: "Clippy Colin", greeting: "Hey. Every light out there is a real commit. In here it's just me and the telemetry." },
  quorum: { name: "The Moderator", greeting: "Three of them are arguing upstairs. Give it a minute; consensus is expensive today." },
  specit: { name: "The Interviewer", greeting: "Sit anywhere. First question: what are you actually trying to build?" },
  "gsd-browser": { name: "The Lab Tech", greeting: "Don't touch the evidence bundles. Or do, they're replayable." },
  openclaw: { name: "The Super", greeting: "Seven floors, every one under renovation. Mind the Slack floor, it's signed." },
  "clippy-colin": { name: "Clippy", greeting: "Oh! A visitor. I've read every commit. Ask me anything, I have receipts." },
  "agent-ops": { name: "Night Shift", greeting: "Six of us on duty, zero automatic writes. Colin's asleep. Probably." },
  "feeling-loopy": { name: "The Hatter", greeting: "Try one on. Everybody looks a little loopy. That's the point." },
};

export const SEED_BUILDINGS: Building[] = [
  {
    id: "seed-loop",
    slug: "the-loop",
    name: "The Loop",
    tagline: "colin.place itself, built by its own agents",
    description: "the website that builds itself",
    kind: "observatory",
    floors: 4,
    footprint: { w: 2, d: 2 },
    palette: { wall: "#1d1a15", roof: "#ff8c42", accent: "#ffb27a" },
    roof: "dome",
    sign: "colin.place",
    features: ["neon", "satellite", "antenna"],
    interior: {
      headline: "A site that narrates itself, with every claim linked to a public page.",
      body: [
        "Every change here is planned, written, tested, and deployed by agent sessions. Colin approves what ships. The agents append their own changelog as they go, so the log is the proof rather than a claim.",
        "The front page draws his real GitHub events along an infinity loop. This town is the next experiment: describe a thing and it gets built, live, on an empty lot.",
      ],
      rooms: [
        { name: "The wire", note: "Live GitHub telemetry, refreshed every minute." },
        { name: "The log", note: "Journal, agent changelog, and workshop builds in one stream." },
        { name: "Colin OS", note: "The original desktop, kept at /os." },
      ],
      question: "What should a personal website do that no personal website does?",
    },
    source: "colin",
    status: "approved",
    createdAt: "2026-07-22T00:00:00Z",
    links: [{ label: "colin.place", href: "https://colin.place" }],
  },
  {
    id: "seed-quorum",
    slug: "quorum",
    name: "Quorum",
    tagline: "the arguing house",
    description: "a machine that argues with itself",
    kind: "library",
    floors: 3,
    footprint: { w: 3, d: 2 },
    palette: { wall: "#cbb994", roof: "#5b3a2e", accent: "#f472b6" },
    roof: "gable",
    sign: "QUORUM",
    features: ["balcony", "banner"],
    interior: {
      headline: "Three models walk in. They debate, critique each other, and vote.",
      body: [
        "Quorum is a multi-AI deliberation framework. Instead of trusting one model's answer, several models argue the question, tear into each other's reasoning, and reach a validated consensus. Sometimes they all agree, wrongly. That is the interesting part.",
        "It exists because a single confident answer is cheap. A consensus that survived an argument is worth something.",
      ],
      rooms: [
        { name: "The floor", note: "Where the debate happens, round by round." },
        { name: "The ballot box", note: "Votes, dissents, and the final position." },
        { name: "Transcripts", note: "Every argument is kept. Reproducible beats persuasive." },
      ],
      question: "When was the last time consensus was expensive enough to mean something?",
    },
    source: "colin",
    status: "approved",
    createdAt: "2026-05-20T00:00:00Z",
    links: [{ label: "Solvely-Colin/Quorum", href: "https://github.com/Solvely-Colin/Quorum" }],
  },
  {
    id: "seed-specit",
    slug: "specit",
    name: "SpecIt",
    tagline: "the interview booth",
    description: "one interview that becomes one spec",
    kind: "booth",
    floors: 1,
    footprint: { w: 2, d: 1 },
    palette: { wall: "#f0e3c8", roof: "#2f6f8f", accent: "#7dd3fc" },
    roof: "flat",
    sign: "SpecIt",
    features: ["awning", "neon"],
    interior: {
      headline: "Sit down. Answer questions. Walk out with a structured spec.",
      body: [
        "SpecIt runs an adaptive interview: it asks what you are building, follows the thread, and writes a .spec file another coding framework can pick up and execute. One conversation in, one spec out.",
        "Written in Go, because the booth should start instantly and never need a runtime installed.",
      ],
      rooms: [
        { name: "The chair", note: "The interview itself. It adapts to your answers." },
        { name: "The printer", note: "Exports to other coding frameworks." },
      ],
      question: "What is the question you wish someone had asked before you started building?",
    },
    source: "colin",
    status: "approved",
    createdAt: "2026-03-16T00:00:00Z",
    links: [{ label: "Solvely-Colin/SpecIt", href: "https://github.com/Solvely-Colin/SpecIt" }],
  },
  {
    id: "seed-gsd-browser",
    slug: "gsd-browser",
    name: "gsd-browser",
    tagline: "the evidence lab",
    description: "a headless browser agents can trust",
    kind: "lab",
    floors: 2,
    footprint: { w: 3, d: 3 },
    palette: { wall: "#d8dde3", roof: "#3b4a5a", accent: "#86efac" },
    roof: "sawtooth",
    sign: "EVIDENCE",
    features: ["satellite", "chimney", "garden"],
    interior: {
      headline: "One install, a full MCP server, and a tarball a reviewer can replay.",
      body: [
        "gsd-browser is GSD's headless-browser CLI for agents, written in Rust. Agents kept fumbling browser setup, so this is one command that works, speaks MCP over stdio, and turns every run into an evidence bundle: per-step screenshots, DOM snapshots, timing logs.",
        "Colin landed 18 merged PRs here, including the replayable evidence schema, Playwright export, and release automation.",
      ],
      rooms: [
        { name: "The bench", note: "Navigation, snapshots, form fills, shadow DOM." },
        { name: "The archive", note: "Evidence bundles anyone can unzip and re-run." },
        { name: "The MCP desk", note: "browser_navigate, browser_snapshot, browser_click, browser_type." },
      ],
      question: "Would you trust a test you could not replay?",
    },
    source: "colin",
    status: "approved",
    createdAt: "2026-07-22T00:00:00Z",
    links: [{ label: "open-gsd/gsd-browser", href: "https://github.com/open-gsd/gsd-browser" }],
  },
  {
    id: "seed-openclaw",
    slug: "openclaw",
    name: "OpenClaw",
    tagline: "the tall one, always under renovation",
    description: "your own personal AI assistant, any OS, any platform",
    kind: "tower",
    floors: 7,
    footprint: { w: 2, d: 2 },
    palette: { wall: "#e9e4d8", roof: "#c9561b", accent: "#fde047" },
    roof: "spire",
    sign: "OpenClaw",
    features: ["antenna", "flag", "balcony"],
    interior: {
      headline: "A personal AI assistant with a floor for every platform.",
      body: [
        "OpenClaw runs on iOS, Android, macOS, the web, Slack, and Discord, with a plugin runtime underneath. Colin is a volunteer maintainer: reviewing PRs, onboarding contributors, and building the QA Lab evidence gallery and CI smoke profile the project runs on.",
        "Twenty-nine merged PRs so far, from Slack signature verification to iPad control surfaces to Discord voice playback.",
      ],
      rooms: [
        { name: "Floor 1: Slack", note: "Signed ingress, external selects, streaming previews." },
        { name: "Floor 4: iOS", note: "Pro UI, gateway flows, Watch actions." },
        { name: "The roof: QA Lab", note: "Evidence artifacts, scenarios, smoke profile in CI." },
      ],
      question: "Which platform is your assistant not on yet?",
    },
    source: "colin",
    status: "approved",
    createdAt: "2026-06-01T00:00:00Z",
    links: [{ label: "openclaw/openclaw", href: "https://github.com/openclaw/openclaw" }],
  },
  {
    id: "seed-clippy",
    slug: "clippy-colin",
    name: "Clippy's Hut",
    tagline: "the mascot lives here",
    description: "a mascot that reads live telemetry and answers with receipts",
    kind: "house",
    floors: 1,
    footprint: { w: 1, d: 1 },
    palette: { wall: "#ffe0b8", roof: "#ff8c42", accent: "#c4b5fd" },
    roof: "gable",
    sign: "ask me",
    features: ["chimney", "garden"],
    interior: {
      headline: "Clippy Colin: briefed on Colin, reads the wire, searches GitHub.",
      body: [
        "The site's mascot went from an FAQ bot to a bounded tool-loop agent. It reads live telemetry, hunts down PR reviews, and answers with the exact URLs it used. It is a tiny on-brand relative of Colin's own AI setup, and it knows it is not him.",
      ],
      rooms: [
        { name: "The desk", note: "Where the questions land." },
        { name: "The window", note: "It reacts when a fresh event hits the wire." },
      ],
      question: "What would you ask a mascot that has read every commit?",
    },
    source: "colin",
    status: "approved",
    createdAt: "2026-07-22T00:00:00Z",
  },
  {
    id: "seed-agents",
    slug: "agent-ops",
    name: "Agent Ops",
    tagline: "the night shift",
    description: "the automation fleet that runs while Colin sleeps",
    kind: "workshop",
    floors: 2,
    footprint: { w: 2, d: 3 },
    palette: { wall: "#2a2622", roof: "#4a4038", accent: "#7dd3fc" },
    roof: "flat",
    sign: "ON DUTY",
    features: ["windmill", "neon", "antenna"],
    interior: {
      headline: "Six automations, hundreds of headless checks a day, zero automatic writes.",
      body: [
        "The fleet observes, verifies, builds locally, and reports. Worker dispatch, code changes, GitHub writes, signing, release, and cleanup all wait for Colin. Its public snapshot lives on the site, sanitized, so visitors can watch the town being kept.",
      ],
      rooms: [
        { name: "The board", note: "Findings, severity, and what is blocked on a human." },
        { name: "The clock", note: "Scheduled runs, on Indiana time." },
      ],
      question: "What should an agent never be allowed to do without you?",
    },
    source: "colin",
    status: "approved",
    createdAt: "2026-07-30T00:00:00Z",
    links: [{ label: "Agent operations", href: "https://colin.place/apps/agent" }],
  },
  {
    id: "seed-hat",
    slug: "feeling-loopy",
    name: "Feeling Loopy",
    tagline: "the hat shop",
    description: "a cap that says Feeling Loopy",
    kind: "arcade",
    floors: 1,
    footprint: { w: 2, d: 1 },
    palette: { wall: "#f3ead9", roof: "#ff8c42", accent: "#ff8c42" },
    roof: "dome",
    sign: "∞",
    features: ["neon", "awning"],
    interior: {
      headline: "The hat is real. So is the loop.",
      body: [
        "It started as a cap. It became the motif for everything: the loop between developers and the tools they trust, the agents that build this site in a loop, the infinity drawn in commits on the front page. This shop sells nothing. It just reminds you why the town is shaped the way it is.",
      ],
      rooms: [{ name: "The mirror", note: "Try it on. Everyone looks a little loopy." }],
      question: "What is the one object that explains your whole thing?",
    },
    source: "colin",
    status: "approved",
    createdAt: "2026-09-02T00:00:00Z",
  },
];
